# Generated by Django 4.2.2 on 2023-07-24 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipoproduto', '0001_initial'),
        ('materiaprima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.FloatField()),
                ('valor', models.FloatField()),
                ('fktipoproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoproduto.tipoproduto')),
                ('materiaprima', models.ManyToManyField(related_name='produtos', to='materiaprima.materiaprima')),
            ],
        ),
    ]
