# Generated by Django 4.2.2 on 2023-07-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipopapel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
    ]
